# Generated by Django 3.2.3 on 2021-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skintoneapp', '0003_alter_userimagedb_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
